name: Build Binaries

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}-${{ matrix.arch }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        arch: [x64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Build binary
        run: |
          export GOOS=${{ matrix.os }}
          export GOARCH=${{ matrix.arch }}
          ./build.sh

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: natsdash-${{ matrix.os }}-${{ matrix.arch }}
          path: natsdash-${{ matrix.os }}-${{ matrix.arch }}
