name: Build Binaries

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        arch: [x64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Build binary
        run: |
          export FGOOS=${{ matrix.os }}
          export FGOARCH=${{ matrix.arch }}
          ./build.sh
        shell: bash  

      - name: Upload binary
        uses: softprops/action-gh-release@v1
        with:
          files: natsdash-*
