name: Build Binaries

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}-${{ matrix.arch }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        arch: [x64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build binary
        run: |
          export GOOS=${{ matrix.os }}
          export GOARCH=${{ matrix.arch }}
          go build -o natsdash-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: natsdash-${{ matrix.os }}-${{ matrix.arch }}
          path: natsdash-${{ matrix.os }}-${{ matrix.arch }}
